#!/usr/bin/env python3

import os
import json
import sys
from subprocess import check_output

script_dir = os.path.dirname(os.path.realpath(sys.argv[0]))
tests_file = os.path.join(script_dir, 'tests.json')

with open(tests_file) as file:    
    tests = json.load(file)

id = sys.argv[1]

output = check_output(['./' + tests[id]['executable']] + tests[id]['arguments'])

actual = [int(s) for s in output.split()]

expected = dict()
expected['1'] = [1, 0]
expected['2'] = [2, 1, 0]
expected['3'] = [3, 2, 1, 0]

if expected[id] == actual:
    exit(0)
else:
    exit(1)
