#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo -ne "$2") > /dev/null
}

case "$1" in
    1)
        assert-equal "./test 2" '1\n0\n'
        ;;
    2)
        assert-equal "./test 3" '2\n1\n0\n'
        ;;
    3)
        assert-equal "./test 4" '3\n2\n1\n0\n'
        ;;
esac
