#!/usr/bin/env python3

import os
import json
import sys
from subprocess import Popen

script_dir = os.path.dirname(os.path.realpath(sys.argv[0]))
tests_file = os.path.join(script_dir, 'tests.json')

with open(tests_file) as file:    
    tests = json.load(file)

id = sys.argv[1]

p = Popen(['./' + tests[id]['executable']] + tests[id]['arguments'])
p.wait()

expected = dict()
expected['1'] = 1
expected['2'] = 0
expected['3'] = 0

if p.returncode == expected[id]:
    exit(0)
else:
    exit(1)
