#ifndef ANGELIX_OUTPUT
#define ANGELIX_OUTPUT(type, expr, id) expr
#endif

/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

//#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
//#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line 147 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) atoi)(char const   *__nptr )  __attribute__((__pure__)) ;
//#line 35 "/home/jlee/Work/semfix/semfix-klee/include/klee/klee.h"
// extern void klee_make_symbolic(void *addr , size_t nbytes , char const   *name ) ;
//#line 5 "test.c"
int tmp___cond  ;
//#line 6 "test.c"
int inject_var  ;
//#line 7 "test.c"
int expect_out  ;
//#line 38
extern int ( /* missing proto */  __assert_fail)() ;
//#line 9 "test.c"
int main(int argc , char **argv ) 
{ 
  int bias ;
  int inhibit ;
  int up_sep ;
  int down_sep ;
  int result ;

  {
//#line 16
//  klee_make_symbolic((void *)(& expect_out), sizeof(expect_out), "expect_out");
//#line 17
//  klee_make_symbolic((void *)(& inject_var), sizeof(inject_var), "inject_var");
//#line 19
  inhibit = atoi((char const   *)*(argv + 1));
//#line 20
  up_sep = atoi((char const   *)*(argv + 2));
//#line 21
  down_sep = atoi((char const   *)*(argv + 3));
//#line 23
  if (inhibit) {
//#line 24
    bias = down_sep; // bias = (up_sep + 100);
  } else {
//#line 27
    bias = up_sep;
  }
//#line 30
  if (bias > down_sep) {
//#line 31
    result = 1;
  } else {
//#line 34
    result = 0;
  }
//#line 37
//  klee_make_symbolic((void *)(& expect_out), sizeof(expect_out), "expect_out");
//#line 38
//  if (! (result == expect_out)) {
//#line 38
//    __assert_fail("result == expect_out", "test.c", 38, "main");
//  }
//#line 39
  printf((char const   * __restrict  )"%d", ANGELIX_OUTPUT(int, result, "result"));
//#line 40
  return (result);
}
}
