#!/bin/bash

assert-equal () {
    diff -q <(${ANGELIX_RUN:-eval} $1) <(echo -ne "$2") > /dev/null
}

case "$1" in
    1)
        assert-equal "./test abc" 'abc\n'
        ;;
    2)
        assert-equal "./test lmn" 'lMN\n'
        ;;
    3)
        assert-equal "./test xyz" 'XYZ\n'
        ;;
esac
