#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo -ne "$2") > /dev/null
}

case "$1" in
    0)
        assert-equal "./test -1" ''
        ;;
    1)
        assert-equal "./test 0" '0\n'
        ;;
    2)
        assert-equal "./test 1" '1\n'
        ;;
    3)
        assert-equal "./test 10" '10\n10\n'
        ;;
    4)
        assert-equal "./test 11" '11\n11\n'
        ;;
esac
