#!/bin/bash

exe="$1"
shift

rm -rf "$ANGELIX_KLEE_WORKDIR"/klee-out-*
rm -rf "$(dirname "$exe")"/klee-out-*

klee -write-smt2s \
     -smtlib-human-readable \
     --libc=uclibc \
     --posix-runtime \
     -allow-external-sym-calls \
     -max-forks=$ANGELIX_KLEE_MAX_FORKS \
     -max-time=$ANGELIX_KLEE_MAX_TIME \
     -max-solver-time=$ANGELIX_KLEE_MAX_SOLVER_TIME \
     "${exe}.patched.bc" \
     "$@"

mv "$(dirname "$exe")"/klee-out-* "$ANGELIX_KLEE_WORKDIR"
