#!/bin/bash

if [[ -n "$ANGELIX_WITH_DUMPING" ]]; then
    export ANGELIX_DUMP="$ANGELIX_WITH_DUMPING"
fi

if [[ -n "$ANGELIX_WITH_TRACING" ]]; then
    export ANGELIX_TRACE="$ANGELIX_WITH_TRACING"
fi

"$@"
